<template>
    <FormKit
      type="text"
      label="Name"
      validation="required"
    />
    <FormKit
      type="email"
      label="Email"
      validation="required|email"
    />
  </template>